# Generated by Django 5.1.1 on 2024-10-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_key',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_name',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
