# Generated by Django 5.1.1 on 2024-10-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_remove_uploadedfile_file_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='original_file_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
